import 'package:mainamwal/model/general_analysis/account_data.dart';

class AccountDataModel extends AccountData {
  const AccountDataModel({
    required super.accountGuid,
    required super.parentGuid,
    required super.accountCode,
    required super.accountName,
    required super.currencyCode,
    required super.openBalance,
    required super.closeBalance,
    required super.accountType,
    required super.typeName,
    required super.aler,
    required super.alerName,
    required super.natural,
    required super.naturalName,
    required super.grossLevel,
    required super.grossLevelName,
    required super.mainDTL,
    required super.mainDTLName,
    required super.totalLevel,
    required super.totalLevelName,
    required super.companyGuid,
    required super.companyName,
    required super.projectGuid,
    required super.projectName,
    required super.costcenterGuid,
    required super.costcenterName,
    required super.number,
  });

  factory AccountDataModel.fromJson(Map<String, dynamic> json) =>
      AccountDataModel(
        accountGuid: json['AccountGuid'] ?? '',
        parentGuid: json['ParentGuid'] ?? '',
        accountCode: json['AccountCode'] ?? '',
        accountName: json['AccountName'] ?? '',
        currencyCode: json['CurrencyCode'] ?? '',
        openBalance: json['OpenBalance'] ?? '',
        closeBalance: json['CloseBalance'] ?? '',
        accountType: json['AccountType'] ?? '',
        typeName: json['TypeName'] ?? '',
        aler: json['ALER'] ?? '',
        alerName: json['ALERName'] ?? '',
        natural: json['Natural'] ?? '',
        naturalName: json['NaturalName'] ?? '',
        grossLevel: json['GrossLevel'] ?? '',
        grossLevelName: json['GrossLevelName'] ?? '',
        mainDTL: json['MainDTL'] ?? '',
        mainDTLName: json['MainDTLName'] ?? '',
        totalLevel: json['TotalLevel'] ?? '',
        totalLevelName: json['TotalLevelName'] ?? '',
        companyGuid: json['CompanyGuid'] ?? '',
        companyName: json['CompanyName'] ?? '',
        projectGuid: json['ProjectGuid'] ?? '',
        projectName: json['ProjectName'] ?? '',
        costcenterGuid: json['CostcenterGuid'] ?? '',
        costcenterName: json['CostcenterName'] ?? '',
        number: json['Number'] ?? '',
      );
}
